apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: prometheus-project
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 27.29.1
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/applications/prometheus/values.yaml
    - repoURL: https://github.com/kaiodt/argocd.git
      targetRevision: HEAD
      ref: values
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=false
      - ApplyOutOfSyncOnly=false
