apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 27.29.1
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/applications/prometheus/values.yaml
    - repoURL: https://github.com/kaiodt/argocd.git
      targetRevision: HEAD
      ref: values
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
