apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos
  namespace: argocd
spec:
  project: chaos-project
  source:
    repoURL: https://github.com/kaiodt/web-page-deploy.git
    path: k8s/chaos
    targetRevision: HEAD
  destination:
    namespace: chaos
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=false
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=false
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: web
      jsonPointers:
        - /spec/replicas
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      name: web
      jsonPointers:
        - /status/currentReplicas
        - /status/desiredReplicas
  