apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    # Source 1: Installs ArgoCD via Helm Chart
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 8.2.5
      helm:
        releaseName: argo-cd
        valueFiles:
          - $values/argocd/values.yaml
    
    # Source 2: Provides values file to ArgoCD's Helm Chart
    - repoURL: https://github.com/kaiodt/argocd.git
      targetRevision: HEAD
      ref: values

    # Source 3: Sync ArgoCD's own Application
    - repoURL: https://github.com/kaiodt/argocd.git
      targetRevision: HEAD
      path: argocd

    # Source 4: Root App - Sync Applications in the applications directory
    - repoURL: https://github.com/kaiodt/argocd.git
      targetRevision: HEAD
      path: applications
      directory:
        recurse: true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=false
      - ApplyOutOfSyncOnly=false
