apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 8.2.5
      helm:
        releaseName: argo-cd
        valueFiles:
          - $values/argocd/values.yaml
    - repoURL: https://github.com/kaiodt/argocd.git
      targetRevision: HEAD
      directory:
        recurse: true
      ref: values
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
