redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1
  service:
    type: LoadBalancer
    servicePortHttp: 8080

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

configs:
  cm:
    timeout.reconciliation: 120s
